"""
Structured Action models returned by the FastAPI backend to the client agent.
"""

from enum import Enum
from typing import Dict, Optional, Any
from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """Supported browser action types."""
    CLICK = "click"
    TYPE = "type"
    SCROLL = "scroll"
    NAVIGATE = "navigate"
    SELECT = "select"
    NONE = "none"


class AgentAction(BaseModel):
    """Structured browser action generated by the agent planner."""
    action: ActionType = Field(..., description="Action type to perform on target page")
    element_id: Optional[str] = Field(None, description="Target element ID (e.g. profile_17 or name_rahul)")
    value: Optional[str] = Field(None, description="Text value for typing or input if applicable")
    reasoning: Optional[str] = Field(None, description="High-level reasoning for choosing this action")
    answer: Optional[str] = Field(None, description="Direct textual answer to user query if goal is achieved or information is found")


class AgentPlanResponse(BaseModel):
    """Top-level agent response containing the planned structured action."""
    status: str = Field("success", description="Planning execution status")
    action: AgentAction = Field(..., description="Structured browser action payload")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Execution metadata or provider stats")
